### ISSUE TITLE
corrected.genePred -genePredExt -allErrors -ignoreGroupsWithoutExons' returned non-zero exit status 255.

### ISSUE THREAD

**Issue by Xingliang888** [ConesaLab/SQANTI3#248]
Hi. 
I degbug  the squanti3 for one whole week, trying to run this program, but many many bugs are emerging sequentially, it seems I can never dissolve them.

I am trying from the samplest one,
python /SQANTI3/SQANTI3/sqanti3_qc.py --fasta 1.output.fastq --force_id_ignore /ref/ensembl/GTF/Mus_musculus.GRCm39.105.gtf =/ref/minimap_mm10/Mus_musculus.GRCm39.dna.toplevel.fa --cpus 30  -d 1.squanti --skipORF
or
python /SQANTI3/SQANTI3/sqanti3_qc.py 1.eb.all.transcripts.gtf --force_id_ignore /ref/ensembl/GTF/Mus_musculus.GRCm39.105.gtf /ref/minimap_mm10/Mus_musculus.GRCm39.dna.toplevel.fa --cpus 30 --report both -d 1.squanti --skipORF

but met the error:
Command '/SQANTI3/SQANTI3/utilities/gtfToGenePred /nanopore/squanti/1.squanti/1.eb.all.transcripts_corrected.gtf transcripts_corrected.genePred -genePredExt -allErrors -ignoreGroupsWithoutExons' returned non-zero exit status 255.

Anyone has ever met this new problem? Thank you

**Comment by carolinamonzo** [comment]
Hi @Xingliang888, 

Thanks for using SQANTI3! Did you try running SQANTI3 with the example files of the tutorial to check if this is a sqanti issue? (https://github.com/ConesaLab/SQANTI3/wiki/Running-SQANTI3-Quality-Control )
The error you copied looks like it's a formatting error in your input GTF.

Best wishes,
Carolina.

**Comment by Xingliang888** [comment]
Hi, Carolina,

Good morning,

I nearly gave up it. Thank you for your response.

The example runs well. But my files did not.

My input GTF are from stringtie, which is including the novel transcripts. The GTF file formats are shown in attached.

Should I do something about the GTF files?


Thank you.

Best,
![GTF_files_from_stringtie](https://github.com/ConesaLab/SQANTI3/assets/157734790/ea9b9ad3-8bf1-469e-86af-96262058ccf6)
![example](https://github.com/ConesaLab/SQANTI3/assets/157734790/0469758c-8953-45b0-ae3b-4c6f110e3326)



Xingliang

**Comment by carolinamonzo** [comment]
Hi @Xingliang888 

Probably your GTF has a strand error, as reported before in other issues (#56 ). You need to filter your GTF so column 7 only contains "+" or "-".

Best,
Carolina.

**Comment by Xingliang888** [comment]
> Hi @Xingliang888
> 
> Probably your GTF has a strand error, as reported before in other issues (#56 ). You need to filter your GTF so column 7 only contains "+" or "-".
> 
> Best, Carolina.

Yes, exactly. The problem has been fixed by remove "." lines. Thank you.

**Comment by cruzreyc** [comment]
Hello, I have also filtered out any "." in Column 7 and still get the same error. I am using a StringTie gtf file.
