### ISSUE TITLE
The isoform classification is not accurate for Genic Intron and Intergenic

### ISSUE THREAD

**Issue by dolittle007** [ConesaLab/SQANTI3#255]
Hi SQANTI3 developers,

I found that SQANTI3 usually identifies genic intron as intergenic by mistake. Could you please fix this issue?

https://github.com/ConesaLab/SQANTI3/blob/a9b660436f0eb3de763d45a05803542f29df4cdf/sqanti3_qc.py#L1335-L1381

Thanks a lot.

**Comment by dolittle007** [comment]
-- Example:
`sqanti3_qc.py test.gtf RNF115_MRNIP_SEC13.gtf hg38.fa --report skip --skipORF -o test`

[example.zip](https://github.com/ConesaLab/SQANTI3/files/14411272/example.zip)

**Comment by alexpan00** [comment]
Hi @dolittle007,

Thanks for your detailed example. I am looking at this right now and let you now as soon as possible.

Alejandro

**Comment by alexpan00** [comment]
Hi @dolittle007,

We have identified the cause of the problem and working on a fix. However, the third isoform of your example would be classified as a genic intron, because it does not overlap with any exon of the transcript in the other strand. This is necessary for an isoform to be classified as antisense.

Thank you,
Alejandro

**Comment by Tang-pro** [comment]
Hi, @alexpan00 
![image](https://github.com/ConesaLab/SQANTI3/assets/149154213/c6806922-50a1-4ac3-a1ac-b0113e142a8e)
![image](https://github.com/ConesaLab/SQANTI3/assets/149154213/36ab03f3-acbd-4885-8b07-43070b207685)
The isoform here is obviously the same as the reference, why is it classified as intergenic?

**Comment by alexpan00** [comment]
Hi @Tang-pro 

Is the reference shorter than 200bp?

Alejandro

**Comment by Tang-pro** [comment]
Hi, @alexpan00 
No, Some are over 200bp, but most are short

**Comment by alexpan00** [comment]
Try using the option  --min_ref_len 0, or just pull the repository and run SQANTI3 again. The default value was changed from 200 to 0 a month ago.

 In the example that you are showing the reference transcripts seem to be quite short, probably under 200 bp, so it is discarded with the previous --min_ref_len default of 200. If the issue persists, please, open a new issue.

**Comment by Tang-pro** [comment]
Hi，@alexpan00 
Yes, indeed, regions greater than 200bp are intergenic, while regions less than 200bp are considered overlapping. Here is another question: Why was the 200bp cutoff chosen at that time? Is there any significance behind this particular number?

**Comment by alexpan00** [comment]
Sorry, @Tang-pro, but I am not sure if I fully understood your answer.  You are saying that there are isoforms in your gtf that overlap a transcript in the reference annotation that is longer than 200bp while the isoform is being classified as intergenic, is this correct? If that is the case, please, open a new issue and provide some examples (in gtf format if possible).

The idea of the 200bp cutoff was introduced to avoid hits with families of small RNAs. After getting a couple of issues reporting incorrect classification on isoforms as intergenic (when the reference is shorter than 200bp), we decided that it may be better to set the default value to 0 and give the user full control of the cutoff.

**Comment by Tang-pro** [comment]
Hi, @alexpan00 
So far, no isoforms larger than 200bp have been found to overlap with the reference. Most of the isoforms smaller than 200bp have this kind of situation.
Thank you very much for your reply

**Comment by alexpan00** [comment]
This issue with the genic intron has been fixed in the last commit #283

**Comment by MengjunWu** [comment]
Hi, I want to ask if this bug is fixed in the latest SQANTI version 5.2.1? I have updated my previous 5.2 to 5.2.1, however this bug still persists

**Comment by alexpan00** [comment]
Hi,
I think this bug was fixed after the release of 5.2.1, could you clone the repository and give it a try?

Alejandro

**Comment by MoMoTPark** [comment]
Hi team, I'm using SQ 5.2.1 and noticed I still get misclassified transcripts as 'intergenic' when they should be 'genic_intronic'. Attached screen shot of both PB.6617.24 and PB.6611.1 which are categorized as intergenic.

Many thanks for your help 

Mo 

```
PB.6617.24      chr1    +       1876    1       intergenic      novelGene_0_40581       novel   NA      NA      NA      NA      NA      NA      mono-exon       FALSE   NA      NA      NA      NANA      15      NA      NA      NA      NA      NA      NA      A       non_coding      NA      NA      NA      NA      NA      NA      NA      75      TTAAAAAAATAAATAAATAA    NA      FALSE   NANA      AGTAAA  -13     TRUE    NA      NA      Artifact
PB.6611.1       chr1    -       1671    1       intergenic      novelGene_0_40582       novel   NA      NA      NA      NA      NA      NA      mono-exon       FALSE   NA      NA      NA      NANA      3       NA      NA      NA      NA      NA      NA      A       non_coding      NA      NA      NA      NA      NA      NA      NA      50      AAGGAAATAAAATCATGTTC    NA      FALSE   NANA      NA      NA      FALSE   NA      NA      Artifact
```
<img width="3008" alt="Screenshot 2024-07-11 at 13 39 59" src="https://github.com/ConesaLab/SQANTI3/assets/87229834/de51823a-e333-4ce8-98a2-dc27e7c7d1d1">

**Comment by alexpan00** [comment]
Hi @MoMoTPark,

This change has not been included in a release yet. You should clone the repo in order to get this change.

Sorry for the inconvenience,
Alejandro

**Comment by MoMoTPark** [comment]
Hi Alejandro,

I see, thank you very much for the prompt reply. I'll do that then.

Many thanks,
Mo
